[package]
name = "tree-rust"
version = "0.2.0"
authors = ["pontakornth <pontakorn61@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = "~2.27.0"
